# Generated by Django 4.1.1 on 2022-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('not-issued', 'Not Issued')], default='not-issued', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
