# Generated by Django 4.1.1 on 2022-09-21 06:44

from django.db import migrations, models
import django.db.models.deletion
import tutorials2_books.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials2_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=tutorials2_books.models.expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tutorials2_books.books')),
            ],
            options={
                'verbose_name': 'Issued Book',
                'verbose_name_plural': 'Issued Books',
            },
        ),
    ]
