# Generated by Django 4.1.1 on 2022-09-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials2_books', '0002_issuedbooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('can_lend', 'Can Lend'), ('can_borrow', 'Can Borrow'), ('can_destroy', 'Can Destroy'), ('can_archive', 'Can Archive'), ('can_sell', 'Can Sell'), ('can_buy', 'Can Buy')), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
